from __future__ import annotations
from io import BytesIO
from datetime import datetime
import uuid
import os

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

from app import models


RECEIPT_DIR = "storage/receipts"
os.makedirs(RECEIPT_DIR, exist_ok=True)


def generate_receipt_number():
    return f"RCPT-{uuid.uuid4().hex[:10].upper()}"


def build_receipt_pdf(payment, tenant, unit, property_, landlord, manager=None) -> tuple[bytes, str]:
    receipt_number = generate_receipt_number()

    file_name = f"{receipt_number}.pdf"
    file_path = os.path.join(RECEIPT_DIR, file_name)

    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)

    w, h = A4
    left = 20 * mm
    y = h - 25 * mm

    # HEADER
    c.setFont("Helvetica-Bold", 16)
    c.drawString(left, y, "PropSmart PMS")
    y -= 10 * mm

    c.setFont("Helvetica-Bold", 14)
    c.drawString(left, y, "PAYMENT RECEIPT")
    y -= 10 * mm

    # RECEIPT INFO
    c.setFont("Helvetica", 11)
    c.drawString(left, y, f"Receipt No: {receipt_number}")
    y -= 6 * mm

    c.drawString(left, y, f"Date: {datetime.utcnow().strftime('%Y-%m-%d %H:%M')}")
    y -= 6 * mm

    c.drawString(left, y, f"Period: {payment.period}")
    y -= 10 * mm

    # PAYMENT DETAILS
    c.setFont("Helvetica-Bold", 12)
    c.drawString(left, y, "Payment Details")
    y -= 6 * mm

    c.setFont("Helvetica", 11)
    c.drawString(left, y, f"Amount: KES {payment.amount}")
    y -= 6 * mm

    c.drawString(left, y, f"Method: M-Pesa")
    y -= 6 * mm

    c.drawString(left, y, f"Transaction Code: {payment.reference or '-'}")
    y -= 10 * mm

    # TENANT
    c.setFont("Helvetica-Bold", 12)
    c.drawString(left, y, "Tenant Details")
    y -= 6 * mm

    c.setFont("Helvetica", 11)
    c.drawString(left, y, f"{tenant.name} ({tenant.phone})")
    y -= 10 * mm

    # PROPERTY
    c.setFont("Helvetica-Bold", 12)
    c.drawString(left, y, "Property Details")
    y -= 6 * mm

    c.setFont("Helvetica", 11)
    c.drawString(left, y, f"{property_.name}")
    y -= 6 * mm

    c.drawString(left, y, f"Unit: {unit.number}")
    y -= 6 * mm

    c.drawString(left, y, f"Property Code: {property_.property_code}")
    y -= 6 * mm

    c.drawString(left, y, f"Address: {property_.address}")
    y -= 10 * mm

    # OWNER / MANAGER
    if landlord:
        c.drawString(left, y, f"Landlord: {landlord.name}")
        y -= 6 * mm

    if manager:
        c.drawString(left, y, f"Agency/Manager: {manager.name}")
        y -= 6 * mm

    y -= 10 * mm

    c.drawString(left, y, "Thank you for your payment.")
    y -= 6 * mm

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(left, y, "Generated by PropSmart PMS")

    c.save()

    pdf_bytes = buf.getvalue()

    # Save file
    with open(file_path, "wb") as f:
        f.write(pdf_bytes)

    return pdf_bytes, file_path, receipt_number