# app/routers/payment_receipts.py
from __future__ import annotations

from io import BytesIO
from datetime import datetime
from decimal import Decimal
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Response
from sqlalchemy.orm import Session

from app.dependencies import get_db, get_current_user
from app import models

# PDF
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.lib import colors

router = APIRouter(prefix="/payments", tags=["Payments: Receipts"])

def _safe_decimal(v) -> Decimal:
    try:
        return Decimal(str(v or "0"))
    except Exception:
        return Decimal("0")

def _receipt_number(p: models.Payment) -> str:
    # Example: PM-000012-20251107
    return f"PM-{p.id:06d}-{(p.paid_date or p.created_at).strftime('%Y%m%d')}"

@router.get("/receipt/{payment_id}.pdf")
def payment_receipt_pdf(
    payment_id: int,
    db: Session = Depends(get_db),
    current: dict = Depends(get_current_user),
):
    """
    Returns a PDF receipt for the given payment id.
    AuthZ:
      - tenant who owns the payment
      - landlord/manager/admin related to the property
    """
    p: Optional[models.Payment] = db.query(models.Payment).filter(models.Payment.id == payment_id).first()
    if not p:
        raise HTTPException(status_code=404, detail="Payment not found")

    # Load relations we need
    t: Optional[models.Tenant] = db.query(models.Tenant).filter(models.Tenant.id == p.tenant_id).first()
    u: Optional[models.Unit] = db.query(models.Unit).filter(models.Unit.id == p.unit_id).first()
    l: Optional[models.Lease] = db.query(models.Lease).filter(models.Lease.id == p.lease_id).first() if p.lease_id else None
    prop: Optional[models.Property] = db.query(models.Property).filter(models.Property.id == (u.property_id if u else 0)).first()
    landlord: Optional[models.Landlord] = db.query(models.Landlord).filter(models.Landlord.id == (prop.landlord_id if prop else 0)).first() if prop else None

    # Basic authZ
    role = current.get("role")
    uid = int(current.get("sub", 0) or 0)

    if role == "tenant":
        if not t or t.id != uid:
            raise HTTPException(status_code=403, detail="Forbidden")
    elif role == "landlord":
        if not prop or not landlord or landlord.id != uid:
            raise HTTPException(status_code=403, detail="Forbidden")
    # managers/admins allowed by default (assuming your get_current_user already asserts real roles)

    # Compose receipt fields
    amount = _safe_decimal(p.amount)
    period = p.period or ""
    paid_date = (p.paid_date or p.created_at or datetime.utcnow()).strftime("%Y-%m-%d")
    reference = p.reference or "-"
    status = p.status.value if hasattr(p.status, "value") else str(p.status)
    receipt_no = _receipt_number(p)

    tenant_name = (t.name if t else "-") or "-"
    tenant_phone = (t.phone if t else "-") or "-"
    unit_label = (u.number if u else "-") or "-"
    property_name = (prop.name if prop else "-") or "-"

    # Create PDF
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    w, h = A4

    x_margin = 20 * mm
    y = h - 25 * mm

    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(x_margin, y, "Payment Receipt")
    y -= 8 * mm
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.grey)
    c.drawString(x_margin, y, "Generated by Property Manager")
    c.setFillColor(colors.black)

    # Divider
    y -= 5 * mm
    c.setStrokeColor(colors.lightgrey)
    c.line(x_margin, y, w - x_margin, y)
    y -= 8 * mm

    # Receipt / meta
    c.setFont("Helvetica-Bold", 11)
    c.drawString(x_margin, y, f"Receipt No.: {receipt_no}")
    y -= 6 * mm
    c.setFont("Helvetica", 10)
    c.drawString(x_margin, y, f"Reference: {reference}")
    y -= 6 * mm
    c.drawString(x_margin, y, f"Status: {status.upper()}")
    y -= 6 * mm
    c.drawString(x_margin, y, f"Paid Date: {paid_date}")
    y -= 10 * mm

    # Property / unit / tenant
    c.setFont("Helvetica-Bold", 11)
    c.drawString(x_margin, y, "Payment For")
    y -= 6 * mm
    c.setFont("Helvetica", 10)
    c.drawString(x_margin, y, f"Property: {property_name}")
    y -= 6 * mm
    c.drawString(x_margin, y, f"Unit: {unit_label}")
    y -= 6 * mm
    c.drawString(x_margin, y, f"Tenant: {tenant_name}   ({tenant_phone})")
    y -= 10 * mm

    # Money
    c.setFont("Helvetica-Bold", 11)
    c.drawString(x_margin, y, "Amount")
    y -= 6 * mm
    c.setFont("Helvetica", 10)
    c.drawString(x_margin, y, f"KES {amount:,.2f}")
    y -= 6 * mm
    c.drawString(x_margin, y, f"Period: {period}")
    y -= 12 * mm

    # Footer
    c.setStrokeColor(colors.lightgrey)
    c.line(x_margin, 25 * mm, w - x_margin, 25 * mm)
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.grey)
    c.drawString(x_margin, 20 * mm, "Thank you. This receipt is system generated and valid without a signature.")
    c.setFillColor(colors.black)

    c.showPage()
    c.save()

    pdf = buf.getvalue()
    buf.close()

    filename = f"receipt_{payment_id}.pdf"
    return Response(
        content=pdf,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'}
    )
