"""fix payment relationships

Revision ID: 1b14747a5306
Revises: 986bc3e7265a
Create Date: 2025-09-12 13:46:32.358037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b14747a5306'
down_revision: Union[str, Sequence[str], None] = '986bc3e7265a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'unit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('payments', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('service_charges', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('service_charges', 'unit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('service_charges', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('service_charges', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('units', 'rent_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('units', 'rent_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('service_charges', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('service_charges', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('service_charges', 'unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('service_charges', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payments', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('payments', 'unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payments', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
