"""add lease terms

Revision ID: 1c663cedf39c
Revises: add_mpesa_request_ids_to_payments
Create Date: 2026-03-24 08:17:20.180571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c663cedf39c'
down_revision: Union[str, Sequence[str], None] = 'add_mpesa_request_ids_to_payments'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_landlord_payouts_id'), table_name='landlord_payouts')
    op.drop_table('landlord_payouts')
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('audit_logs', 'message',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'actor_role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               nullable=True)
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.create_index('ix_audit_logs_property_created', 'audit_logs', ['property_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_property_id'), 'audit_logs', ['property_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'properties', ['property_id'], ['id'])
    op.drop_column('audit_logs', 'ip_address')
    op.drop_column('audit_logs', 'meta_json')
    op.drop_column('audit_logs', 'user_agent')
    op.add_column('leases', sa.Column('terms_text', sa.String(), nullable=True))
    op.add_column('leases', sa.Column('terms_accepted', sa.Integer(), nullable=True))
    op.add_column('leases', sa.Column('terms_accepted_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('fk_leases_tenant_id_tenants'), 'leases', type_='foreignkey')
    op.drop_constraint(op.f('fk_leases_unit_id_units'), 'leases', type_='foreignkey')
    op.alter_column('maintenance_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index('ix_payments_checkout_request_id_not_null', 'payments', ['checkout_request_id'], unique=False)
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=False)
    op.drop_constraint(op.f('fk_payments_tenant_id_tenants'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('fk_payments_lease_id_leases'), 'payments', type_='foreignkey')
    op.drop_index(op.f('uq_units_property_norm_number'), table_name='units')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_units_property_norm_number'), 'units', ['property_id', sa.literal_column('lower(TRIM(BOTH FROM number))')], unique=True)
    op.create_foreign_key(op.f('fk_payments_lease_id_leases'), 'payments', 'leases', ['lease_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_payments_tenant_id_tenants'), 'payments', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.drop_index('ix_payments_checkout_request_id_not_null', table_name='payments')
    op.alter_column('maintenance_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_foreign_key(op.f('fk_leases_unit_id_units'), 'leases', 'units', ['unit_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_leases_tenant_id_tenants'), 'leases', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.drop_column('leases', 'terms_accepted_at')
    op.drop_column('leases', 'terms_accepted')
    op.drop_column('leases', 'terms_text')
    op.add_column('audit_logs', sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('meta_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('ip_address', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_property_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_property_created', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor_role', 'actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'actor_role',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('audit_logs', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.create_table('landlord_payouts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payout_type', postgresql.ENUM('mpesa_paybill', 'mpesa_till', 'mpesa_phone', 'bank', name='payouttype'), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('paybill', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('paybill_account', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('till_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mpesa_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bank_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bank_branch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bank_account_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bank_account_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], name=op.f('landlord_payouts_landlord_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('landlord_payouts_pkey')),
    sa.UniqueConstraint('landlord_id', 'payout_type', 'paybill', 'till_number', 'mpesa_phone', 'bank_name', 'bank_account_number', name=op.f('uq_landlord_payout_unique_combo'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_landlord_payouts_id'), 'landlord_payouts', ['id'], unique=False)
    # ### end Alembic commands ###
