"""fix payment relationships

Revision ID: 74668739e4cb
Revises: 387aad083c44
Create Date: 2025-09-12 14:00:01.422668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74668739e4cb'
down_revision: Union[str, Sequence[str], None] = '387aad083c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leases', sa.Column('rent_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('leases', sa.Column('active', sa.Integer(), nullable=True))
    op.alter_column('leases', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('leases', 'unit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('leases', 'start_date',
               existing_type=sa.String(),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('leases', 'end_date',
               existing_type=sa.String(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('properties', 'landlord_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('units', 'property_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('units', 'property_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('properties', 'landlord_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('leases', 'end_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('leases', 'start_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('leases', 'unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('leases', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('leases', 'active')
    op.drop_column('leases', 'rent_amount')
    # ### end Alembic commands ###
