"""initial tables

Revision ID: 9dd8cb16e1e1
Revises: 74668739e4cb
Create Date: 2025-09-12 14:12:27.210227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd8cb16e1e1'
down_revision: Union[str, Sequence[str], None] = '74668739e4cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('lease_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'leases', ['lease_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'lease_id')
    # ### end Alembic commands ###
